# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubInfo', '0005_auto_20170924_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='author',
        ),
    ]
