# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubInfo', '0007_announcement_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='author',
            new_name='auth',
        ),
    ]
