# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ClubInfo', '0009_auto_20170925_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 21, 42, 21, 86828, tzinfo=utc), verbose_name='date published'),
        ),
    ]
