# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ClubInfo', '0011_auto_20170925_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Taken'),
        ),
    ]
