# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubInfo', '0013_auto_20171030_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='contest_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='contest_name',
            new_name='name',
        ),
    ]
