# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 04:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubInfo', '0015_auto_20171030_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
