# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubInfo', '0018_auto_20171105_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
