# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-10 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubInfo', '0019_auto_20180304_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='out_of',
        ),
        migrations.AddField(
            model_name='contest',
            name='out_of',
            field=models.IntegerField(default=5),
        ),
    ]
