# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubInfo', '0020_auto_20180309_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
